
const HOST = window.location.href;
const STEPS_PER_FRAME = 5;
const WORLD_GRAVITY = 10;
const PLAYER_SPEED = 8;
const PLAYER_ON_FLOOR_SPEED = 8;
const PLAYER_MOUSE_SENSITIVITY = 500;

export {
    HOST,
    STEPS_PER_FRAME,
    WORLD_GRAVITY,
    PLAYER_SPEED,
    PLAYER_ON_FLOOR_SPEED,
    PLAYER_MOUSE_SENSITIVITY,
}